version: '3.8'
services:
  frontend:
    container_name: frontend
    platform: linux/x86_64
    build: ./frontend
    ports:
      - 3000:5173
      - 5173:5173
    working_dir: /frontend
    volumes:
      - ./frontend/src:/frontend/src
    depends_on:
      - backend
  backend:
    container_name: backend
    platform: linux/x86_64
    build: ./backend
    ports:
      - 3001:3001
    working_dir: /backend
    volumes:
      - ./backend/src:/backend/src
    depends_on:
      - db
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=cashforce
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: 'always'
